import time
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from django.db import connection
from django.db.models import Count
from django.test import Client
from django.test.utils import CaptureQueriesContext

from orders.models import Customer


class Command(BaseCommand):
    help = (
        "Profile the broken vs fixed summary endpoint: prints SQL query counts "
        "and timings, records both requests in django-silk, and writes the "
        "results to evidence/profiling.md."
    )

    def handle(self, *args, **options):
        customer = (
            Customer.objects.annotate(order_count=Count("orders"))
            .order_by("-order_count")
            .first()
        )
        if customer is None or customer.order_count == 0:
            raise CommandError("No order data found - run `python manage.py seed_orders` first.")

        urls = {
            "broken": f"/api/orders/summary-broken/?customer={customer.pk}",
            "fixed": f"/api/orders/summary/?customer={customer.pk}",
        }
        client = Client()

        # Pass 1 - raw numbers. Silk interception is turned off so its own
        # bookkeeping INSERTs don't pollute the capture.
        silk_config = self._silk_config()
        if silk_config:
            silk_config.SILKY_INTERCEPT_PERCENT = 0

        results = {}
        for name, url in urls.items():
            with CaptureQueriesContext(connection) as ctx:
                started = time.perf_counter()
                response = client.get(url)
                elapsed_ms = (time.perf_counter() - started) * 1000
            if response.status_code != 200:
                raise CommandError(f"{url} returned {response.status_code}")
            results[name] = {"queries": len(ctx.captured_queries), "ms": elapsed_ms}

        # Pass 2 - let silk record one request per endpoint so the reviewer can
        # inspect them at /silk/ as well.
        silk_counts = {}
        if silk_config:
            silk_config.SILKY_INTERCEPT_PERCENT = 100
            for name, url in urls.items():
                client.get(url)
            try:
                from silk.models import Request

                for name, url in urls.items():
                    path = url.split("?")[0]
                    recorded = (
                        Request.objects.filter(path=path)
                        .order_by("-start_time")
                        .first()
                    )
                    if recorded:
                        silk_counts[name] = recorded.queries.count()
            except Exception as exc:  # silk internals moved - not fatal
                self.stderr.write(f"Could not read silk request data: {exc}")

        report = self._render_report(customer, results, silk_counts)
        self.stdout.write(report)

        evidence_dir = Path(settings.BASE_DIR) / "evidence"
        evidence_dir.mkdir(exist_ok=True)
        out = evidence_dir / "profiling.md"
        out.write_text(report, encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"\nWritten to {out}"))
        if silk_counts:
            self.stdout.write(
                "Both requests are also recorded in django-silk - start the dev "
                "server and open http://localhost:8000/silk/ to inspect them."
            )

    def _silk_config(self):
        try:
            from silk.config import SilkyConfig

            return SilkyConfig()
        except Exception:
            return None

    def _render_report(self, customer, results, silk_counts):
        broken, fixed = results["broken"], results["fixed"]
        speedup = broken["ms"] / fixed["ms"] if fixed["ms"] else float("inf")
        lines = [
            "# Section 1 - profiler evidence",
            "",
            f"Dataset: customer id={customer.pk} with {customer.order_count} orders (SQLite, local).",
            "Generated by `python manage.py profile_summary`.",
            "",
            "| Endpoint | SQL queries | Wall time |",
            "|---|---|---|",
            f"| `/api/orders/summary-broken/` | {broken['queries']} | {broken['ms']:.0f} ms |",
            f"| `/api/orders/summary/` (fixed) | {fixed['queries']} | {fixed['ms']:.0f} ms |",
            "",
            f"Query count: {broken['queries']} -> {fixed['queries']}; "
            f"wall time ~{speedup:.0f}x faster on localhost.",
            "",
            "The gap widens dramatically with real network latency: at ~1ms of",
            "round-trip time per query, the broken endpoint pays that cost per",
            "order, the fixed one pays it twice in total.",
        ]
        if silk_counts:
            lines += [
                "",
                "django-silk recorded the same requests "
                f"(broken: {silk_counts.get('broken', '?')} queries, "
                f"fixed: {silk_counts.get('fixed', '?')} queries) - "
                "browse them at `/silk/` with the dev server running.",
            ]
        return "\n".join(lines) + "\n"
